framework:
  website: doc.networknt.com
  version: 2.3

  build:
    - mvn clean package -Prelease

  binaries:
    - target/benchmark-1.0.0.jar

  files:
    - "src/**/*.yml"

  command: >
    /usr/bin/java -jar target/benchmark-1.0.0.jar
