framework:
  github: chubbyts/chubbyts-framework
  version: 2.0

  engines:
    - uwebsockets

  bootstrap:
    - npm -g install typescript
    - npm install
    - tsc

language:
  engines:
    uwebsockets:
      environment:
        NODE_APP: app.js
